Keep ref_ext on update facture line
ATM-Consulting/dolibarr_module_subtotal pull request #277
Opened 2022-07-25 10:13 UTC by EchoLoGeek

2022-07-25 12:15 UTC, atm-john requested changes

2022-07-25 12:15 UTC, atm-john commented on class/subtotal.class.php
> +}
Mistake ?

2022-07-26 13:16 UTC, EchoLoGeek commented on class/subtotal.class.php
> +}
Yes i think, i have forked 3.11 version and just update subtotal.class.php on line 802, function doUpdateLine and facture feature, in order to add the external ref. Maybe I've made an error.

2022-10-07 12:14 UTC, atm-john commented on lib/subtotal.lib.php
> +				$res = TSubtotal::doUpdateLine($object, $line->id, $line->desc, $line->subprice, $line->qty, $line->remise_percent, $line->date_start, $line->date_end, $subtotal_tva_tx, $line->product_type, $lin
ref ext isn't a param

2022-10-07 12:14 UTC, closed without merging